### ISSUE TITLE
On the chopping block: UDKExplorer

### ISSUE THREAD

**Issue by Mgamerz** [ME3Tweaks/LegendaryExplorer#121]
@Kinkojiro What functionality of UDKExplorer is not present in ME3Explorer? You said meshes don't work... or something like that? There is no 3D viewer in UDK explorer (if I recall) so it shouldn't be too difficult to move it into the toolset.

**Comment by Kinkojiro** [comment]
If you are copying a mesh from (3ds ->) UDK to ME1/2/3 you can via hex editing because the sections vary in known ways.  However it is much much easier if you can see the layout in UDK editor - bone names, bounding boxes, LODs etc.  Meshplorer only works with ME3.  UDK explorer shows the layout in the meshplorer portion.

Ideally the layout view could be ported to meshplorer or even better to replace the binary view of the packEd page for meshes.

**Comment by Kinkojiro** [comment]
The porting of meshplorer Unreal Meshplorer to Binary Interpreter has been done via commit 5382165264ae3c79ec0e961a73d3d55c22eb5adf

UDK Explorer should be able to be removed.

**Comment by Mgamerz** [comment]
This has been axed in 4.1 Shader Cache Branch and will be promoted into Beta once 4.0 ships.
