### ISSUE TITLE
Tools icons too big on Win7

### ISSUE THREAD

**Issue by Tajfun403** [ME3Tweaks/LegendaryExplorer#123]
When on Windows 7, icons of tools placed in PackageEditorWPF's menus are rendered too big. They're correct on Win10.

Screenshot: 
![srgsgr](https://user-images.githubusercontent.com/44444384/57536688-f5c7e780-7344-11e9-89b4-7d90a7518d85.png)

Relevant links:
https://stackoverflow.com/questions/42447757/c-sharp-wpf-button-picture-looks-differently-on-windows-7-and-windows-10
https://stackoverflow.com/questions/45356692/wpf-program-designed-on-windows-10-doesnt-scale-on-windows-7-correctly

**Comment by Mgamerz** [comment]
Looking at the relevant links we can either force a style or somehow override them globally and set the icon heights. I don't know much about the latter, but the former would require us to include the theme dll from Windows 10, at least until Windows 7 becomes unsupported in January.

Since I don't have a Windows 7 system to test with, this might be something more in @SirCxyrtyx 's domain.
