### ISSUE TITLE
Bug minor: binary editor wwise event doesn't allow editing

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Tweaks/LegendaryExplorer#14]
"Set Value" doesn't work.

**Comment by Mgamerz** [comment]
Doesn't sound like a wise event sounds like a dumb event

**Comment by Mgamerz** [comment]
Can you get a filename/export # so I can reproduce this? I have lost the original ones I made it with.

**Comment by Mgamerz** [comment]
This should be fixed by 1e9d10e097a1d4e2cd3bc3b7cfc79e3262fb8f9f in this class and other ones that could not edit the final values if their data started within the last 7 bytes of the file. Now data that starts within the last 3 bytes will not work - I don't think I write anything smaller than an int so this shouldn't be an issue unless it is writing a name - I may need to make the code more robust depending on the node type being written.

**Comment by Kinkojiro** [comment]
That works for wwise events thank you.  However on class binaries the final int does not appear in the dialogue box and you cannot change it.  Very minor thing, but you may be right about the code.

**Comment by Mgamerz** [comment]
Please verify this in 3.0.9 so I can close this issue.

**Comment by Kinkojiro** [comment]
Yes this is fixed thank you
