### ISSUE TITLE
Dumping ME2 stumbles on multiple copies of BioD_Nor_103Messages.pcc

### ISSUE THREAD

**Issue by mirh** [ME3Tweaks/LegendaryExplorer#167]
**Describe the bug**
I'm dumping ME2, when a "this file is already in use" error appears. 
After some logging, I found out this happens because multiple copies of the same file exists in the game folder. 

**Steps to reproduce the behavior:**
1. Install some DLC I guess? From Zaeed to Firewalker it seems like every one of them has a copy of this file. 
2. Open package dumper and dump all ME2

**Expected behavior**
If a "dump txt file" already exists in a folder, I suppose extraction should be skipped altogther? User should be warned for that, but you are just begging for weird behaviors otherwise (even [mods](https://www.nexusmods.com/Core/Libs/Common/Widgets/FileContentPopUp?game_id=264&file_id=552) can ship with the same file)
And of course, there should be a mechanism to still make extract happen, when you can trace back similar file names to different DLCs positions (for example, they could be renamed to "*original-file-name (DLC_whatever)*")

**Version information:**
4.1.1

**Stack trace**
```
IOException: The process cannot access the file 'D:\YaddaYadda\BioD_Nor_103Messages.txt' because it is being used by another process.
   in System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   in System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   in System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   in System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   in System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   in System.IO.StreamWriter..ctor(String path)
   in ME3Explorer.PackageDumper.PackageDumperSingleFileTask.dumpPackageFile()
   in ME3Explorer.PackageDumper.PackageDumper.<dumpPackages>b__62_0(PackageDumperSingleFileTask x)
   in System.Threading.Tasks.Dataflow.ActionBlock`1.ProcessMessage(Action`1 action, KeyValuePair`2 messageWithId)
   in System.Threading.Tasks.Dataflow.ActionBlock`1.<>c__DisplayClass5.<.ctor>b__0(KeyValuePair`2 messageWithId)
   in System.Threading.Tasks.Dataflow.Internal.TargetCore`1.ProcessMessagesLoopCore()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   in ME3Explorer.PackageDumper.PackageDumper.<dumpPackages>d__62.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   in ME3Explorer.PackageDumper.PackageDumper.<dumpPackagesFromFolder>d__61.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   in System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Other information**
On a separate note... Is it normal that by now ME3Explorer.exe is taking ***5GB*** of ram?

**Comment by Mgamerz** [comment]
Good point on the overrides and multithreading issues. I did not consider this case.

We will resume working on ME3Explorer beta branch in next couple of weeks once I finished Mod Manager Build 104.

Mgamerz

From: mirh
Sent: Monday, March 2, 2020 6:08 AM
To: ME3Tweaks/ME3Explorer
Cc: Subscribed
Subject: [ME3Tweaks/ME3Explorer] Dumping ME2 stumbles on multiple copies ofBioD_Nor_103Messages.pcc (#167)

Describe the bug
I'm dumping ME2, when a "this file is already in use" error appears.
After some logging, I found out this happens because multiple copies of the same file exists in the game folder.
Steps to reproduce the behavior:
1. Install some DLC I guess? From Zaeed to Firewalker it seems like every one of them has a copy of this file.
2. Open package dumper and dump all ME2
Expected behavior
If a "dump txt file" already exists in a folder, I suppose extraction should be skipped altogther? User should be warned for that, but you are just begging for weird behaviors otherwise (even mods can ship with the same file)
And of course, there should be a mechanism to still make extract happen, when you can trace back similar file names to different DLCs positions (for example, they could be renamed to "original-file-name (DLC_whatever)")
Version information:
4.1.1
Stack trace
IOException: The process cannot access the file 'D:\YaddaYadda\BioD_Nor_103Messages.txt' because it is being used by another process.

   in System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

   in System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)

   in System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)

   in System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)

   in System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)

   in System.IO.StreamWriter..ctor(String path)

   in ME3Explorer.PackageDumper.PackageDumperSingleFileTask.dumpPackageFile()

   in ME3Explorer.PackageDumper.PackageDumper.<dumpPackages>b__62_0(PackageDumperSingleFileTask x)

   in System.Threading.Tasks.Dataflow.ActionBlock`1.ProcessMessage(Action`1 action, KeyValuePair`2 messageWithId)

   in System.Threading.Tasks.Dataflow.ActionBlock`1.<>c__DisplayClass5.<.ctor>b__0(KeyValuePair`2 messageWithId)

   in System.Threading.Tasks.Dataflow.Internal.TargetCore`1.ProcessMessagesLoopCore()

--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---

   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   in System.Runtime.CompilerServices.TaskAwaiter.GetResult()

   in ME3Explorer.PackageDumper.PackageDumper.<dumpPackages>d__62.MoveNext()

--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---

   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   in System.Runtime.CompilerServices.TaskAwaiter.GetResult()

   in ME3Explorer.PackageDumper.PackageDumper.<dumpPackagesFromFolder>d__61.MoveNext()

--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---

   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   in System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   in System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Other information
On a separate note... Is it normal that by now ME3Explorer.exe is taking 5GB of ram?

**Comment by Kinkojiro** [comment]
This is caused by multithreading when dumping packages that are arranged in alphabetical order.  A quick and easy fix is to randomise the sort order of the packages.

**Comment by Mgamerz** [comment]
I think it would be better to just append a number or the dlc folder name
to the file in a try catch. I will look into fixing this when I have some
time in the next couple of days.

**Comment by mirh** [comment]
This doesn't seem to be fixed with ME1
(which doesn't have DLCs with duplicate names, but you can just create a subfolder yourself and copy paste some file)

**Comment by mirh** [comment]
Actktually, it's back also for ME2 (I'm using latest 2163 nightly)
