### ISSUE TITLE
Bug very minor: Package Ed - save hex in import header not working

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Tweaks/LegendaryExplorer#18]
Ancient bug, but still.

**Comment by Mgamerz** [comment]
Want to check in on this bug and make sure it is still active - on my end from testing, it does actually save but it doesn't refresh stuff on the export, forcing you to click away and then back into it. I remember asking for this feature a long time ago and it was rejected - can you confirm it is not actually saving?

I can make it so that the export reloads when saving.

**Comment by Kinkojiro** [comment]
This still is there and clicking away doesn't fix it.

Click on an import in Tree View.  Header Raw:  edit something, click save, click away.  Click back, not changed.

**Comment by Mgamerz** [comment]
OK I will look into this.

**Comment by Mgamerz** [comment]
Can you verify this works in 3.0.9v2.

**Comment by Kinkojiro** [comment]
Yes this works now.  Thank you.
