### ISSUE TITLE
Better Wwisebank editing functionality

### ISSUE THREAD

**Issue by beccatoria** [ME3Tweaks/LegendaryExplorer#242]
**Is your feature request related to a problem? Please describe.**
Currently the ability to edit audio in wwisebanks (beyond replacements via soundplorer) is limited to hex editing

**Describe the solution you'd like**
Research into and implementation of any known ways to edit wwisebanks via gui instead of hex.

**Describe alternatives you've considered**
None, this is a placeholder feature request.

**Additional context**
Tapatalk thread on wwisebank research: https://www.tapatalk.com/groups/me3explorer/current-research-wwisebanks-t867-s10.html

This includes information on how to hex edit audio and various other elements, so that it is not lost to the sands of time.

**Comment by mirh** [comment]
[This](https://wiki.xentax.com/index.php/Wwise_SoundBank_(*.bnk)) is probably more comprehensive.

**Comment by Mgamerz** [comment]
That documentation is not correct for the versions of wwise our games use. Almost none of it is applicable.

**Comment by mirh** [comment]
Sorry for the dupe. 
https://www.tapatalk.com/groups/me3explorer/new-ish-tool-audio-editor-t2540-s30.html

**Comment by Mgamerz** [comment]
I'm closing this as we are not going to be pursuing this avenue of audio editing since we now have a fairly decent understanding of importing Wwise audio (for LE - we don't have the required info for OT, and scene is effectively dead anyways). 

Once the dev team has some time we will build tools to import directly from Wwise output. Right now we have mostly a proof of concept that it works but is very tedious without adequate tooling and our development focus is currently elsewhere.
