### ISSUE TITLE
Open Assets for Line in Matinee's nLineStrRef (FOVO)

### ISSUE THREAD

**Issue by SpaceD0lphin** [ME3Tweaks/LegendaryExplorer#258]
**PROBLEM**
I work with a lot of FOVO nodes. FOVO nodes essentially act as shells; they contain a STR Ref with the right subtitle and the right camera data, but their voice/FXA assets are located in elsewhere, usually in a different conversation. In editing these, a lot of back-and-forth-ing has to be done by remembering what line is what in the other conversation being used to borrow from. It's easy to lose track of. I sometimes need multiple FXAs and Interps open at once so I can keep track of what flows into what. I have accidentally animated the wrong nodes a few times because of this.

**SOLUTION**
A way to minimise having to go back and forth through the different conversations and manually remember what lines correspond to new audio.
Being able to open the "donor" line's assets from within a given BioFOVOTrackData would be immensely useful.
Adding the following options to a right click menu would save so much time and headache:

- Open Line Audio (M) (Opens the line's Male audio asset in Sound Explorer, ready for replacement)
- Open Line Audio (F) (Opens the line's Female audio asset in Sound Explorer, ready for replacement)
- Open Line FXA (M) (Opens the line's Male FXA in FFXE)
- Open Line FXA (F) (Opens the line's Female FXA in FFXE)

**Additional context**

![image](https://user-images.githubusercontent.com/79815367/124368794-bb281400-dc5c-11eb-96ee-f24889539cae.png)
This image shows where this option could appear. Alternatively, it could appear by right-clicking the FOVO track in the Conversation Group (although I suspect doing so by expanding the FOVO's data proper may be easier to implement.)

**BONUS:** In the black bar where "Add InterpGroup" is located, displaying the node's String Reference Text aligned to the right would be very useful. When multiple Interps are open, having a way to easily reference what line they correspond to would also be immensely useful.

**Comment by henbagle** [comment]
I've added the four requested options in the latest nightly. Rather than adding them as context menu items (which can be sort of complicated to change between track types), I've added them as experiments in a new experiment sub-heading "Open Assets for Selected Track"

You must have a SFXInterpTrackPlayFaceOnlyVO track selected in the timeline for these buttons to do anything. Also, they will only open the assets for the first BioFOVOTrackData key in the track. If having multiple FOVO keys in a track is a common technique, we could look into an option to select one of them.

![image](https://user-images.githubusercontent.com/8151477/138192633-3a3070f6-5c68-42b0-a3b6-8a35e06ab413.png)
