### ISSUE TITLE
Export/Import Texture Issues

### ISSUE THREAD

**Issue by ghost** [ME3Tweaks/LegendaryExplorer#264]
As per discord:

Exporting LE2 normal textures causes issues where the colours are wrong, they change from blue/pinks to oranges/greens, that causes a lot of issues when importing them back into the game. Not only this, but edited normals imported into LE3 can have their colours changed if the normal is imported as a .png.

One of the textures I tried this with was Rock04_Norm from LE2

**Comment by Mgamerz** [comment]
Please follow the report template.

# Please fill out the following form *in its entirety*. 
The more information you provide, the easier it will be for us to work with.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Be specific. Reports must include tool names, filenames, export numbers and more so that we can reproduce the issue. **Do not use generic "use any file" or "any tool". Be specific. If specific reproducible steps are not included, we may simply close the issue as not reproducible.**

Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error


**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots and files used to replicate this**
If applicable, add screenshots to help explain your problem.

**Version information:**
Please include both the date and version number that is located on the left side of the main window. **This information is required**.

**Stack trace**
If you see an error dialog with a details or copy button, please post the details here. 

**Other information**
Add any other context about the problem here.

**Comment by ghost** [comment]
**Describe the bug**
Exporting LE2 normal textures causes issues where the colours are wrong, they change from blue/pinks to oranges/greens, that causes a lot of issues when importing them back into the game. Not only this, but edited normals imported into LE3 can have their colours changed if the normal is imported as a .png.

One of the textures I tried this with was Rock04_Norm from LE2

**To Reproduce LE2 Normal issues**
- Open Asset Database or Package Editor
- Locate an LE2 normal texture
- Export texture
- Texture will have different colours than it should have

It might look like the following image:
https://i.imgur.com/9GTF2GP.png?1

**To Reproduce LE3 Normal issues**
- Open pcc in Package Editor
- Find a normal texture of similar dimensions to the normal texture exported above from LE2
- Clone this texture
- "Import from File"; import the LE2 normal texture over this clone 
 
It might look like the following image:
https://i.imgur.com/WRnIsZW.png?1

**Version information:**
The version before the stable, I think. The tools updated since my original bug report

**Comment by ghost** [comment]
This appears to also be happening with LE2 Diff textures sometimes, as seen when trying to export SCI_ARM_Diff from BioD_EndGm2_300Walk04.pcc

**Comment by ghost** [comment]
The same bug is happening with Norm files being exported from LE1 too. For example:

PCC File = BioA_Nor10_02_DS1.pcc
Norm Texture = Export 7279 HMM_HAT_GCM_Norm

The same method to extract the textures is used as above

**Comment by ghost** [comment]
The same bug is happening with Norm files being exported from ME1 too. For example:

PCC File = BioA_Nor10_02_DS1.pcc
Norm Texture = Export 7279 HMM_HAT_GCM_Norm

The same method to extract the textures is used as above

This is on the latest nightly

**Comment by Mgamerz** [comment]
This should hopefully be fixed now. If you have time, please test it out (it's on the latest nightly).
