### ISSUE TITLE
SoundplorerWPF: WEM Replacement not working

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Tweaks/LegendaryExplorer#56]
When replacing a WEM inside the bank it causes the bank to stop working.

Attached to discord is a sample zip:
SFXWeapon_Pistol_Carnifex.pcc
SFXWeapon_Pistol_Carnifex_ORIGINAL.pcc (unmodded)
Wwise_Weapons_S_Carnifex_0x11850B92.wav   Extracted "folding" sound from the same file (1st WEM in Wwise_Weapons_S_Carnifex)

Replace the WEM 0 (0x004C8849) in Wwise_Weapons_P_Carnifex  bank with the extracted sound.

Try in game - there is no weapon firing sound.

NOTES: 
Possible cause maybe incorrect offsets.  Note In the original file wwise the next RIFF starts at WEM 0 (length) + 4bytes
These extra 4 bytes are the ID that precedes every WEM in the DATA/DIDX

Notes on DISCORD

**Comment by Mgamerz** [comment]
My current code writes a WEM directly following. I was not aware there was data between the files - you say there is 4 bytes data length and 4 bytes ID? (there appears to be 8 bytes missing between mine).

**Comment by Mgamerz** [comment]
After doing a deeper analysis there appears to be some byte alignment going on to a 16 byte boundary. However upon doing so we are still seeing serial size mismatch. Cause is unknown right now. We may consider replacing a bank with only 1 wem and see what the outcome is.

**Comment by Mgamerz** [comment]
This has been fixed by 314552e2092aaf56f0e5ddea3dee372c60b3aca4. The issue was twofold:
 - Items in DATA must be aligned to a 16-byte boundary,
 - The header preceeding the actual bnk file must be updated with the proper offset and size. The Wwise Editor already in ME3Explorer did this, but the code was written in a way that it was obfuscated and not easy to determine.
