### ISSUE TITLE
WPF Binary Scan conversion class WIP list

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Tweaks/LegendaryExplorer#57]
List of binary scans to be converted -> WPF:
~~StartBioDynamicAnimSetScan~~
~~StartBioStageScan~~
~~StartClassScan~~
~~StartClassScan2~~
~~StartEnumScan~~
StartGenericScan
~~StartGUIDCacheScan~~
~~StartLevelScan~~
~~StartMaterialScan~~
~~StartObjectRedirectorScan~~
~~StartPrefabInstanceScan~~
~~StartSkeletalMeshScan~~
~~StartStaticMeshCollectionActorScan~~
~~StartStaticMeshScan~~
~~StartTextureBinaryScan~~
~~StartTextureMovieScan(edited)~~

**Comment by SirCxyrtyx** [comment]
I'm working on these, but since I probably won't end up doing all of them, here are some helpful regexes for anyone else doing them (for use with VS's find and replace feature). You'll probably want to make the scope of the find and replace be just the function you're working on

find: 
`TreeNode\((\$".+").+\n(\s+){`
replace: 
<code>TreeViewItem\n$2{\n$2&nbsp;&nbsp;&nbsp;&nbsp;Header = $1,</code>

find: 
<code>&nbsp;Name = (.+,?)</code>
replace 
<code>&nbsp;Name = "_" + $1</code>

**Comment by SirCxyrtyx** [comment]
I've done all of them now except 
StartGenericScan
StartBioStageScan is partially done.

These both require more functionality to be added to BinaryInterpreterWPF to work.

**Comment by Mgamerz** [comment]
Properties can now be read - however an editor interface will need to be added to Binary Interpreter WPF. I know for sure some of my new scanners do not set node types so I will have to go back and set those. We can probably clone most of the editor set elements code from Interpreter WPF and base it on the nodeTypes. We will probably need new ones for things like uint16 and uint8.

**Comment by Mgamerz** [comment]
This should be *mostly* implemented now. I am sure there are some edge cases I missed. Also need to figure out how to code up arraylengthcontainers. May be done as tree or something with a new data type like ArrayLengthContainer and it's children as the array items. When adding or removing a node it would add/remove the data and then go up the tree and modify the value.

**Comment by Kinkojiro** [comment]
Great work.  
We can call this done.  There are some minor edge cases (mainly other core.property = StringRefProperty, NameProperty, StructProperty, StrProperty, ByteProperty).  I cannot find a case where generic will be used.
