### ISSUE TITLE
Missing minor NAV points

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Tweaks/LegendaryExplorer#6]
Following NAV classes for henchmen are missing:

SFXNav_InteractionHenchOmniTool
SFXNav_InteractionHenchOmniToolCrouch
SFXNav_InteractionHenchBeckonFront
SFXNav_InteractionHenchBeckonRear
SFXNav_InteractionHenchCustom
SFXNav_InteractionHenchCover
SFXNav_InteractionHenchCrouch
SFXNav_InteractionHenchInteractLow
SFXNav_InteractionHenchManual
SFXNav_InteractionHenchStandIdle
SFXNav_InteractionHenchStandTying
SFXNav_InteractionUseConsole
SFXNav_InteractionStandGuard

**Comment by Mgamerz** [comment]
For future reference these navigation points are exports in the file themselves rather than imports, so adding them to a level is significantly more work. This issue is that they weren't visible in Pathfinding Editor. At some point in the future adding them may be an option but it will require significant relinking on binary class objects.

**Comment by Kinkojiro** [comment]
Minor further one to add:  
Engine.PathNode_Dynamic
Core.Class

**Comment by Mgamerz** [comment]
This node is throwing an error due to parsing when it tries to read out of bounds - it will require a bit more work to do this class.
