### ISSUE TITLE
Feature: Nullify export and optionally subtrees

### ISSUE THREAD

**Issue by Mgamerz** [ME3Tweaks/LegendaryExplorer#87]
When porting content sometimes it is easier to just use the whole original file instead. However sometimes you don't want all of the extra garbage included in those items, but there's no real way to remove them.

A feature that would be useful is a right click menu in Package Editor WPF that would have an option to "nullify" an export, and optionally its children exports, by setting the class to package and writing a blank package. We could potentially save some memory at run time by moving all garbage stuff to a garbage top level package and then use a consistent naming scheme below it, that way if this is used across multiple files it won't try to load a bunch of garbage packages.

**Comment by Kinkojiro** [comment]
A good idea. Definitely will need to do the moving/renaming idea to avoid needed things being lost.

I would also consider revising the saving of DLCs if you were to do this:  move to a system where the save is optimized around the shadercache (similar to MEM) rather than just appending copies of tables.

**Comment by Mgamerz** [comment]
This has been implemented in the current dev build.
